name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    wc_coupons_ab1: public._airbyte_raw_wc_coupons
    wc_coupons_ab2: public._airbyte_raw_wc_coupons
    wc_coupons_stg: public._airbyte_raw_wc_coupons
    wc_coupons_scd: public._airbyte_raw_wc_coupons
    wc_coupons: public._airbyte_raw_wc_coupons
    wc_customers_ab1: public._airbyte_raw_wc_customers
    wc_customers_ab2: public._airbyte_raw_wc_customers
    wc_customers_stg: public._airbyte_raw_wc_customers
    wc_customers_scd: public._airbyte_raw_wc_customers
    wc_customers: public._airbyte_raw_wc_customers
    wc_orders_ab1: public._airbyte_raw_wc_orders
    wc_orders_ab2: public._airbyte_raw_wc_orders
    wc_orders_stg: public._airbyte_raw_wc_orders
    wc_orders_scd: public._airbyte_raw_wc_orders
    wc_orders: public._airbyte_raw_wc_orders
    wc_products_ab1: public._airbyte_raw_wc_products
    wc_products_ab2: public._airbyte_raw_wc_products
    wc_products_stg: public._airbyte_raw_wc_products
    wc_products_scd: public._airbyte_raw_wc_products
    wc_products: public._airbyte_raw_wc_products
    wc_products_variations_ab1: public._airbyte_raw_wc_products_variations
    wc_products_variations_ab2: public._airbyte_raw_wc_products_variations
    wc_products_variations_stg: public._airbyte_raw_wc_products_variations
    wc_products_variations_scd: public._airbyte_raw_wc_products_variations
    wc_products_variations: public._airbyte_raw_wc_products_variations
    wc_coupons__links_ab1: public._airbyte_raw_wc_coupons
    wc_coupons__links_ab2: public._airbyte_raw_wc_coupons
    wc_coupons__links_ab3: public._airbyte_raw_wc_coupons
    wc_coupons__links: public._airbyte_raw_wc_coupons
    wc_coupons_meta_data_ab1: public._airbyte_raw_wc_coupons
    wc_coupons_meta_data_ab2: public._airbyte_raw_wc_coupons
    wc_coupons_meta_data_ab3: public._airbyte_raw_wc_coupons
    wc_coupons_meta_data: public._airbyte_raw_wc_coupons
    wc_customers__links_ab1: public._airbyte_raw_wc_customers
    wc_customers__links_ab2: public._airbyte_raw_wc_customers
    wc_customers__links_ab3: public._airbyte_raw_wc_customers
    wc_customers__links: public._airbyte_raw_wc_customers
    wc_customers_billing_ab1: public._airbyte_raw_wc_customers
    wc_customers_billing_ab2: public._airbyte_raw_wc_customers
    wc_customers_billing_ab3: public._airbyte_raw_wc_customers
    wc_customers_billing: public._airbyte_raw_wc_customers
    wc_customers_shipping_ab1: public._airbyte_raw_wc_customers
    wc_customers_shipping_ab2: public._airbyte_raw_wc_customers
    wc_customers_shipping_ab3: public._airbyte_raw_wc_customers
    wc_customers_shipping: public._airbyte_raw_wc_customers
    wc_customers_meta_data_ab1: public._airbyte_raw_wc_customers
    wc_customers_meta_data_ab2: public._airbyte_raw_wc_customers
    wc_customers_meta_data_ab3: public._airbyte_raw_wc_customers
    wc_customers_meta_data: public._airbyte_raw_wc_customers
    wc_orders__links_ab1: public._airbyte_raw_wc_orders
    wc_orders__links_ab2: public._airbyte_raw_wc_orders
    wc_orders__links_ab3: public._airbyte_raw_wc_orders
    wc_orders__links: public._airbyte_raw_wc_orders
    wc_orders_billing_ab1: public._airbyte_raw_wc_orders
    wc_orders_billing_ab2: public._airbyte_raw_wc_orders
    wc_orders_billing_ab3: public._airbyte_raw_wc_orders
    wc_orders_billing: public._airbyte_raw_wc_orders
    wc_orders_refunds_ab1: public._airbyte_raw_wc_orders
    wc_orders_refunds_ab2: public._airbyte_raw_wc_orders
    wc_orders_refunds_ab3: public._airbyte_raw_wc_orders
    wc_orders_refunds: public._airbyte_raw_wc_orders
    wc_orders_shipping_ab1: public._airbyte_raw_wc_orders
    wc_orders_shipping_ab2: public._airbyte_raw_wc_orders
    wc_orders_shipping_ab3: public._airbyte_raw_wc_orders
    wc_orders_shipping: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_ab1: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_ab2: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_ab3: public._airbyte_raw_wc_orders
    wc_orders_fee_lines: public._airbyte_raw_wc_orders
    wc_orders_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_meta_data: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_ab1: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_ab2: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_ab3: public._airbyte_raw_wc_orders
    wc_orders_tax_lines: public._airbyte_raw_wc_orders
    wc_orders_line_items_ab1: public._airbyte_raw_wc_orders
    wc_orders_line_items_ab2: public._airbyte_raw_wc_orders
    wc_orders_line_items_ab3: public._airbyte_raw_wc_orders
    wc_orders_line_items: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_ab1: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_ab2: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_ab3: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_ab1: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_ab2: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_ab3: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines: public._airbyte_raw_wc_orders
    wc_products__links_ab1: public._airbyte_raw_wc_products
    wc_products__links_ab2: public._airbyte_raw_wc_products
    wc_products__links_ab3: public._airbyte_raw_wc_products
    wc_products__links: public._airbyte_raw_wc_products
    wc_products_meta_data_ab1: public._airbyte_raw_wc_products
    wc_products_meta_data_ab2: public._airbyte_raw_wc_products
    wc_products_meta_data_ab3: public._airbyte_raw_wc_products
    wc_products_meta_data: public._airbyte_raw_wc_products
    wc_products_variations__links_ab1: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_ab2: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_ab3: public._airbyte_raw_wc_products_variations
    wc_products_variations__links: public._airbyte_raw_wc_products_variations
    wc_products_variations_meta_data_ab1: public._airbyte_raw_wc_products_variations
    wc_products_variations_meta_data_ab2: public._airbyte_raw_wc_products_variations
    wc_products_variations_meta_data_ab3: public._airbyte_raw_wc_products_variations
    wc_products_variations_meta_data: public._airbyte_raw_wc_products_variations
    wc_coupons__links_self_ab1: public._airbyte_raw_wc_coupons
    wc_coupons__links_self_ab2: public._airbyte_raw_wc_coupons
    wc_coupons__links_self_ab3: public._airbyte_raw_wc_coupons
    wc_coupons__links_self: public._airbyte_raw_wc_coupons
    wc_coupons__links_collection_ab1: public._airbyte_raw_wc_coupons
    wc_coupons__links_collection_ab2: public._airbyte_raw_wc_coupons
    wc_coupons__links_collection_ab3: public._airbyte_raw_wc_coupons
    wc_coupons__links_collection: public._airbyte_raw_wc_coupons
    wc_customers__links_self_ab1: public._airbyte_raw_wc_customers
    wc_customers__links_self_ab2: public._airbyte_raw_wc_customers
    wc_customers__links_self_ab3: public._airbyte_raw_wc_customers
    wc_customers__links_self: public._airbyte_raw_wc_customers
    wc_customers__links_collection_ab1: public._airbyte_raw_wc_customers
    wc_customers__links_collection_ab2: public._airbyte_raw_wc_customers
    wc_customers__links_collection_ab3: public._airbyte_raw_wc_customers
    wc_customers__links_collection: public._airbyte_raw_wc_customers
    wc_orders__links_self_ab1: public._airbyte_raw_wc_orders
    wc_orders__links_self_ab2: public._airbyte_raw_wc_orders
    wc_orders__links_self_ab3: public._airbyte_raw_wc_orders
    wc_orders__links_self: public._airbyte_raw_wc_orders
    wc_orders__links_collection_ab1: public._airbyte_raw_wc_orders
    wc_orders__links_collection_ab2: public._airbyte_raw_wc_orders
    wc_orders__links_collection_ab3: public._airbyte_raw_wc_orders
    wc_orders__links_collection: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes_ab1: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes_ab2: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes_ab3: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_meta_data: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_tax_lines_meta_data: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_ab1: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_ab2: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_ab3: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes: public._airbyte_raw_wc_orders
    wc_orders_line_items_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_line_items_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_line_items_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_line_items_meta_data: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_coupon_lines_meta_data: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_ab1: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_ab2: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_ab3: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_meta_data: public._airbyte_raw_wc_orders
    wc_products__links_self_ab1: public._airbyte_raw_wc_products
    wc_products__links_self_ab2: public._airbyte_raw_wc_products
    wc_products__links_self_ab3: public._airbyte_raw_wc_products
    wc_products__links_self: public._airbyte_raw_wc_products
    wc_products__links_collection_ab1: public._airbyte_raw_wc_products
    wc_products__links_collection_ab2: public._airbyte_raw_wc_products
    wc_products__links_collection_ab3: public._airbyte_raw_wc_products
    wc_products__links_collection: public._airbyte_raw_wc_products
    wc_products_variations__links_self_ab1: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_self_ab2: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_self_ab3: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_self: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_collection_ab1: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_collection_ab2: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_collection_ab3: public._airbyte_raw_wc_products_variations
    wc_products_variations__links_collection: public._airbyte_raw_wc_products_variations
    wc_orders_fee_lines_taxes_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_fee_lines_taxes_meta_data: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_line_items_taxes_meta_data: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_meta_data_ab1: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_meta_data_ab2: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_meta_data_ab3: public._airbyte_raw_wc_orders
    wc_orders_shipping_lines_taxes_meta_data: public._airbyte_raw_wc_orders
